import { Router } from "express";
import { authenticate } from "../../middleware/auth.middleware";
import { requireOrganization } from "../../middleware/organization.middleware";
import { requireActiveEmployeeProfile, requirePermission } from "../../middleware/permissions.middleware";
import { validate } from "../../middleware/validation.middleware";
import * as controller from "./contracts.controller";
import { contractParams, contractQuery, createContractSchema, organizationParams, signEmploymentContractSchema, updateContractSchema, contractTemplateParams, contractTemplateSchema, generateContractVersionSchema, sendForSignatureSchema, signatureFieldParams, signContractFieldSchema } from "./contracts.validation";

export const contractsRoutes = Router();
const inside = [authenticate, validate({ params: organizationParams }), requireOrganization] as const;
contractsRoutes.get("/organizations/:orgSlug/contracts", ...inside, requirePermission("contracts.read"), validate({ query: contractQuery }), controller.listContracts);
contractsRoutes.get("/organizations/:orgSlug/contracts-summary", ...inside, requirePermission("contracts.read"), controller.summary);contractsRoutes.get("/organizations/:orgSlug/contracts/templates", ...inside, requirePermission("contracts.read"), controller.listTemplates);
contractsRoutes.post("/organizations/:orgSlug/contracts/templates", ...inside, requirePermission("contracts.create"), validate({ body: contractTemplateSchema }), controller.createTemplate);
contractsRoutes.patch("/organizations/:orgSlug/contracts/templates/:templateId", ...inside, requirePermission("contracts.update"), validate({ params: contractTemplateParams, body: contractTemplateSchema }), controller.updateTemplate);
contractsRoutes.get("/organizations/:orgSlug/contracts/:contractId/workspace", authenticate, validate({ params: contractParams }), requireOrganization, requirePermission("contracts.read"), controller.workspace);
contractsRoutes.get("/organizations/:orgSlug/contracts/:contractId/workspace/preview", authenticate, validate({ params: contractParams }), requireOrganization, requirePermission("contracts.read"), controller.previewWorkspaceDocument);
contractsRoutes.get("/organizations/:orgSlug/contracts/:contractId/workspace/document", authenticate, validate({ params: contractParams }), requireOrganization, requirePermission("contracts.read"), controller.downloadWorkspaceDocument);
contractsRoutes.post("/organizations/:orgSlug/contracts/:contractId/workspace/versions", authenticate, validate({ params: contractParams, body: generateContractVersionSchema }), requireOrganization, requirePermission("contracts.update"), controller.generateVersion);
contractsRoutes.post("/organizations/:orgSlug/contracts/:contractId/workspace/send", authenticate, validate({ params: contractParams, body: sendForSignatureSchema }), requireOrganization, requirePermission("contracts.update"), controller.sendForSignature);
contractsRoutes.post("/organizations/:orgSlug/contracts/:contractId/workspace/remind-signature", authenticate, validate({ params: contractParams }), requireOrganization, requirePermission("contracts.update"), controller.remindSignature);
contractsRoutes.patch("/organizations/:orgSlug/contracts/:contractId/workspace/signatures/:fieldId", authenticate, validate({ params: signatureFieldParams, body: signContractFieldSchema }), requireOrganization, requirePermission("contracts.update"), controller.signEmployerField);
// A personal, self-scoped view. Employees never obtain the company contract register.
contractsRoutes.get("/organizations/:orgSlug/my-contracts", ...inside, requireActiveEmployeeProfile, controller.listMyContracts);
contractsRoutes.get("/organizations/:orgSlug/my-contracts/:contractId/preview", authenticate, validate({ params: contractParams }), requireOrganization, requireActiveEmployeeProfile, controller.previewMyContractDocument);
contractsRoutes.get("/organizations/:orgSlug/my-contracts/:contractId/document", authenticate, validate({ params: contractParams }), requireOrganization, requireActiveEmployeeProfile, controller.downloadMyContractDocument);
contractsRoutes.patch("/organizations/:orgSlug/my-contracts/:contractId/sign", authenticate, validate({ params: contractParams, body: signEmploymentContractSchema }), requireOrganization, requireActiveEmployeeProfile, controller.signMyEmploymentContract);contractsRoutes.get("/organizations/:orgSlug/my-contracts/:contractId/workspace", authenticate, validate({ params: contractParams }), requireOrganization, requireActiveEmployeeProfile, controller.myWorkspace);
contractsRoutes.patch("/organizations/:orgSlug/my-contracts/:contractId/workspace/signatures/:fieldId", authenticate, validate({ params: signatureFieldParams, body: signContractFieldSchema }), requireOrganization, requireActiveEmployeeProfile, controller.signEmployeeField);
contractsRoutes.post("/organizations/:orgSlug/contracts", ...inside, requirePermission("contracts.create"), validate({ body: createContractSchema }), controller.createContract);
contractsRoutes.patch("/organizations/:orgSlug/contracts/:contractId", authenticate, validate({ params: contractParams }), requireOrganization, requirePermission("contracts.update"), validate({ body: updateContractSchema }), controller.updateContract);
contractsRoutes.delete("/organizations/:orgSlug/contracts/:contractId", authenticate, validate({ params: contractParams }), requireOrganization, requirePermission("contracts.delete"), controller.deleteContract);