"use client";

import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { BadgeCheck, CircleUserRound, ShieldCheck } from "lucide-react";
import { ApiError } from "@/lib/api";
import { changePassword } from "@/lib/auth";
import { useLanguage } from "@/providers/language-provider";

type EmployeeAccount = { employee: { employeeNumber: string; fullName: string; member?: { email?: string | null } | null } };
const text = (fr: boolean, english: string, french: string) => fr ? french : english;

function Card({ title, description, icon: Icon, children }: { title: string; description: string; icon: typeof ShieldCheck; children: React.ReactNode }) {
  return <section className="overflow-hidden rounded-2xl border border-border-strong/80 bg-surface-1 shadow-[0_18px_42px_-32px_rgba(15,23,42,.5)]"><div className="flex gap-3 border-b border-border bg-[linear-gradient(115deg,rgba(20,184,166,.07),transparent_52%)] px-5 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl border border-brand/20 bg-brand-subtle text-brand shadow-sm"><Icon className="size-4" aria-hidden /></span><div><h2 className="text-sm font-semibold text-ink">{title}</h2><p className="mt-0.5 max-w-xl text-xs leading-5 text-ink-secondary">{description}</p></div></div>{children}</section>;
}

export function MyAccountProfile({ account }: { account: EmployeeAccount }) {
  const { locale } = useLanguage(); const fr = locale.startsWith("fr");
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [validationError, setValidationError] = useState<string | null>(null);
  const updatePassword = useMutation({ mutationFn: () => changePassword(currentPassword, newPassword), onSuccess: () => { setCurrentPassword(""); setNewPassword(""); setConfirmation(""); window.setTimeout(() => window.location.assign("/login?passwordChanged=1"), 500); } });
  const passwordError = validationError ?? (updatePassword.error instanceof ApiError ? updatePassword.error.message : updatePassword.error ? text(fr, "We could not change your password. Please try again.", "Votre mot de passe n’a pas pu être modifié. Réessayez.") : null);
  const submitPassword = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!currentPassword) { setValidationError(text(fr, "Enter your current password.", "Saisissez votre mot de passe actuel.")); return; }
    if (newPassword.length < 10 || !/[a-z]/.test(newPassword) || !/[A-Z]/.test(newPassword) || !/[0-9]/.test(newPassword)) { setValidationError(text(fr, "Use at least 10 characters, including an uppercase letter, a lowercase letter and a number.", "Utilisez au moins 10 caractères, avec une majuscule, une minuscule et un chiffre.")); return; }
    if (newPassword === currentPassword) { setValidationError(text(fr, "Choose a new password different from your current password.", "Choisissez un nouveau mot de passe différent de l’actuel.")); return; }
    if (newPassword !== confirmation) { setValidationError(text(fr, "The new passwords do not match.", "Les nouveaux mots de passe ne correspondent pas.")); return; }
    setValidationError(null); updatePassword.mutate();
  };
  const email = account.employee.member?.email ?? "—";
  const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-border bg-surface-1 px-3 text-sm text-ink outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20";
  return <main className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6 lg:p-8">
    <section className="relative isolate overflow-hidden rounded-[1.65rem] border border-white/15 bg-[#0a315d] px-5 py-6 text-white shadow-[0_26px_58px_-34px_rgba(7,36,76,.88)] sm:px-7 sm:py-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_8%_-30%,rgba(115,205,255,.42),transparent_44%),radial-gradient(circle_at_92%_5%,rgba(69,211,170,.22),transparent_28%)]" aria-hidden /><div className="relative flex min-w-0 items-start gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl border border-white/20 bg-white/10 text-blue-50 shadow-lg shadow-black/10"><CircleUserRound className="size-7" aria-hidden /></span><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-100/85">{text(fr, "My account", "Mon compte")}</p><h1 className="mt-1 truncate text-2xl font-semibold tracking-[-.035em] sm:text-3xl">{account.employee.fullName}</h1><p className="mt-1 truncate text-sm text-blue-50/90">{email}</p></div></div></section>
    <Card title={text(fr, "Account details", "Informations du compte")} description={text(fr, "Your identity and the email used to sign in to LiteHubs.", "Votre identité et l’adresse e-mail utilisée pour vous connecter à LiteHubs.")} icon={CircleUserRound}><dl className="grid gap-px bg-border sm:grid-cols-2"><div className="bg-surface-1 px-5 py-4"><dt className="text-xs font-medium text-ink-muted">{text(fr, "Full name", "Nom complet")}</dt><dd className="mt-1 text-sm font-semibold text-ink">{account.employee.fullName}</dd></div><div className="bg-surface-1 px-5 py-4"><dt className="text-xs font-medium text-ink-muted">{text(fr, "Sign-in email", "E-mail de connexion")}</dt><dd className="mt-1 break-all text-sm font-semibold text-ink">{email}</dd></div><div className="bg-surface-1 px-5 py-4"><dt className="text-xs font-medium text-ink-muted">{text(fr, "Employee number", "Matricule")}</dt><dd className="mt-1 text-sm font-semibold text-ink">#{account.employee.employeeNumber}</dd></div><div className="bg-surface-1 px-5 py-4"><dt className="text-xs font-medium text-ink-muted">{text(fr, "Account status", "Statut du compte")}</dt><dd className="mt-1 inline-flex items-center gap-1.5 text-sm font-semibold text-good"><BadgeCheck className="size-4" aria-hidden />{text(fr, "Active", "Actif")}</dd></div></dl></Card>
    <Card title={text(fr, "Password and security", "Mot de passe et sécurité")} description={text(fr, "Change your password. LiteHubs signs out your other sessions to protect your account.", "Modifiez votre mot de passe. LiteHubs ferme vos autres sessions pour protéger votre compte.")} icon={ShieldCheck}><form className="space-y-5 p-5 sm:p-6" onSubmit={submitPassword} noValidate><div className="rounded-xl border border-brand/20 bg-brand-subtle/70 px-3.5 py-3 text-sm leading-6 text-ink-secondary"><ShieldCheck className="mr-1.5 inline size-4 text-brand" aria-hidden />{text(fr, "Use at least 10 characters, including an uppercase letter, a lowercase letter and a number.", "Utilisez au moins 10 caractères, avec une majuscule, une minuscule et un chiffre.")}</div>{passwordError ? <p className="rounded-xl border border-critical/40 bg-critical/10 px-3.5 py-3 text-sm text-critical" role="alert">{passwordError}</p> : null}<label className="block text-sm font-semibold text-ink">{text(fr, "Current password", "Mot de passe actuel")}<input value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} type="password" autoComplete="current-password" className={inputClass} /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold text-ink">{text(fr, "New password", "Nouveau mot de passe")}<input value={newPassword} onChange={(event) => setNewPassword(event.target.value)} type="password" autoComplete="new-password" className={inputClass} /></label><label className="block text-sm font-semibold text-ink">{text(fr, "Confirm new password", "Confirmer le nouveau mot de passe")}<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} type="password" autoComplete="new-password" className={inputClass} /></label></div><div className="flex flex-wrap items-center gap-3 border-t border-border pt-5"><button type="submit" disabled={updatePassword.isPending} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-brand/90 disabled:cursor-not-allowed disabled:opacity-60">{updatePassword.isPending ? text(fr, "Updating…", "Mise à jour…") : text(fr, "Change password", "Modifier le mot de passe")}</button><p className="text-xs leading-5 text-ink-muted">{text(fr, "You will need to sign in again after the change.", "Vous devrez vous reconnecter après la modification.")}</p></div></form></Card>
  </main>;
}