"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Activity, AlertTriangle, BarChart3, Bird, Boxes, CalendarDays, Download, FileSpreadsheet, LandPlot, PiggyBank, RefreshCw, ShieldAlert, Sprout, UsersRound, Wallet } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState, ErrorState, NoAccessState, SkeletonCard } from "@/components/ui/states";
import { get, orgApiUrl, orgUrl } from "@/lib/api";
import { can } from "@/lib/permissions";
import { useLanguage } from "@/providers/language-provider";
import { useSessionUser } from "@/stores/session-store";

type Location = { id: string; name: string; code?: string | null; provinceId?: string | null; province_id?: string | null; isActive?: boolean };
type Currency = { currency: string; planned: number; approvedExpenses: number; paidExpenses: number; pendingExpenses: number; available: number };
type Report = {
  organization: { name: string; currency: string };
  range: { from: string; to: string; provinceId: string | null; siteId: string | null };
  access: Record<string, boolean>;
  poultry: { activeFlocks: number; liveBirds: number; mortality: number; feedKg: number; eggs: number } | null;
  pigs: { pens: number; activeAnimals: number; feedKg: number; mortality: number } | null;
  agriculture: { farms: number; fields: number; activePlantings: number; operations: number; labourHours: number; harvests: number; harvestKg: number } | null;
  work: { openTasks: number; completedTasks: number; overdueTasks: number; dailyReports: number; awaitingReview: number } | null;
  governance: { activeProjects: number; openAlerts: number; criticalAlerts: number; pendingApprovals: number };
  inventory: { items: number; lowStock: number; warehouses: number } | null;
  procurement: { awaitingRequests: number; approvedRequests: number; openOrders: number; receivedOrders: number } | null;
  finance: { currencies: Currency[] } | null;
  people: { activeEmployees: number; onLeave: number } | null;
  generatedAt: string;
};

type Tab = "overview" | "operations" | "work" | "finance";
const dateValue = (daysAgo = 0) => { const day = new Date(); day.setDate(day.getDate() - daysAgo); return day.toISOString().slice(0, 10); };
const integer = (value: number | undefined | null) => new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 1 }).format(Number(value ?? 0));
const money = (value: number, currency: string, locale: string) => new Intl.NumberFormat(locale, { style: "currency", currency: /^[A-Z]{3}$/.test(currency) ? currency : "USD", maximumFractionDigits: 0 }).format(value);

export function ReportsArea({ orgSlug }: { orgSlug: string }) {
  const { locale } = useLanguage();
  const fr = locale === "fr";
  const user = useSessionUser();
  const allowed = can(user, "reports.read");
  const exportAllowed = can(user, "reports.export");
  const [from, setFrom] = useState(() => dateValue(29));
  const [to, setTo] = useState(() => dateValue());
  const [provinceId, setProvinceId] = useState("");
  const [siteId, setSiteId] = useState("");
  const [tab, setTab] = useState<Tab>("overview");
  const filters = useMemo(() => {
    const params = new URLSearchParams({ from, to });
    if (provinceId) params.set("provinceId", provinceId);
    if (siteId) params.set("siteId", siteId);
    return params.toString();
  }, [from, to, provinceId, siteId]);
  const report = useQuery({ queryKey: ["reports", orgSlug, filters], queryFn: () => get<{ report: Report }>(orgUrl(orgSlug, `reports/overview?${filters}`)).then((data) => data.report), enabled: allowed });
  const provinces = useQuery({ queryKey: ["report-provinces", orgSlug], queryFn: () => get<{ provinces: Location[] }>(orgUrl(orgSlug, "provinces")).then((data) => data.provinces), enabled: allowed });
  const sites = useQuery({ queryKey: ["report-sites", orgSlug], queryFn: () => get<{ sites: Location[] }>(orgUrl(orgSlug, "sites")).then((data) => data.sites), enabled: allowed });
  const visibleSites = (sites.data ?? []).filter((site) => !provinceId || (site.provinceId ?? site.province_id) === provinceId);
  const exportUrl = (type: "pdf" | "xlsx") => orgApiUrl(orgSlug, `reports/export.${type}?${filters}&lang=${fr ? "fr" : "en"}`);

  if (!allowed) return <NoAccessState what={fr ? "les rapports" : "reports"} />;
  if (report.isLoading) return <main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6 lg:p-8"><SkeletonCard /><SkeletonCard /><SkeletonCard /></main>;
  if (report.error) return <main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><ErrorState title={fr ? "Impossible de charger les rapports" : "Could not load reports"} description={(report.error as Error).message} onRetry={() => void report.refetch()} /></main>;
  const data = report.data;
  if (!data) return null;

  const tabs: Array<{ id: Tab; fr: string; en: string }> = [
    { id: "overview", fr: "Vue d’ensemble", en: "Overview" },
    { id: "operations", fr: "Production", en: "Operations" },
    { id: "work", fr: "Travail & conformité", en: "Work & compliance" },
    { id: "finance", fr: "Finances & ressources", en: "Finance & resources" },
  ];
  const urgent = data.governance.criticalAlerts + (data.work?.overdueTasks ?? 0) + (data.inventory?.lowStock ?? 0);

  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="overflow-hidden rounded-3xl border border-border bg-[radial-gradient(circle_at_90%_5%,rgba(32,185,150,.22),transparent_30%),linear-gradient(130deg,rgba(9,49,91,.97),rgba(18,91,136,.96))] p-6 text-white shadow-[0_22px_60px_-38px_rgba(11,53,90,.9)] sm:p-7">
      <div className="flex flex-wrap items-start justify-between gap-5">
        <div className="max-w-2xl"><div className="flex items-center gap-2 text-emerald-100"><BarChart3 className="size-5" /><span className="text-sm font-semibold">{fr ? "Pilotage de l’entreprise" : "Business control"}</span></div><h1 className="mt-3 text-3xl font-semibold tracking-[-.035em]">{fr ? "Rapports" : "Reports"}</h1><p className="mt-2 text-sm leading-6 text-sky-50/90">{fr ? "Une lecture claire des opérations, ressources, alertes et dépenses, fondée uniquement sur les données auxquelles vous avez accès." : "A clear view of operations, resources, alerts and spending, based only on data you are allowed to access."}</p></div>
        <div className="flex flex-wrap gap-2">{exportAllowed ? <><a href={exportUrl("pdf")} download className="inline-flex h-10 items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-3 text-sm font-semibold text-white transition hover:bg-white/20"><Download className="size-4" />PDF</a><a href={exportUrl("xlsx")} download className="inline-flex h-10 items-center gap-2 rounded-xl bg-white px-3 text-sm font-semibold text-sky-900 shadow-sm transition hover:bg-sky-50"><FileSpreadsheet className="size-4" />Excel</a></> : null}<Button variant="secondary" className="border-white/20 bg-white/10 text-white hover:bg-white/20" onClick={() => void report.refetch()}><RefreshCw />{fr ? "Actualiser" : "Refresh"}</Button></div>
      </div>
      <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><HeroMetric label={fr ? "Période analysée" : "Period analysed"} value={`${data.range.from} → ${data.range.to}`} icon={CalendarDays} /><HeroMetric label={fr ? "Alertes ouvertes" : "Open alerts"} value={integer(data.governance.openAlerts)} note={data.governance.criticalAlerts ? `${integer(data.governance.criticalAlerts)} ${fr ? "critiques" : "critical"}` : fr ? "Aucune critique" : "No critical"} icon={ShieldAlert} danger={data.governance.criticalAlerts > 0} /><HeroMetric label={fr ? "Travail à surveiller" : "Work to watch"} value={integer(data.work?.overdueTasks)} note={fr ? "tâches en retard" : "overdue tasks"} icon={AlertTriangle} danger={(data.work?.overdueTasks ?? 0) > 0} /><HeroMetric label={fr ? "Points d’attention" : "Attention points"} value={integer(urgent)} note={fr ? "à traiter dans le périmètre" : "inside current scope"} icon={Activity} danger={urgent > 0} /></div>
    </header>

    <section className="rounded-2xl border border-border bg-surface-1 p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Filter label={fr ? "Du" : "From"}><input className="control" type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></Filter><Filter label={fr ? "Au" : "To"}><input className="control" type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></Filter><Filter label={fr ? "Province" : "Province"}><select className="control" value={provinceId} onChange={(event) => { setProvinceId(event.target.value); setSiteId(""); }}><option value="">{fr ? "Toutes les provinces" : "All provinces"}</option>{(provinces.data ?? []).map((province) => <option key={province.id} value={province.id}>{province.name}</option>)}</select></Filter><Filter label={fr ? "Site / ferme" : "Site / farm"}><select className="control" value={siteId} onChange={(event) => setSiteId(event.target.value)}><option value="">{fr ? "Tous les sites" : "All sites"}</option>{visibleSites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></Filter><div className="flex items-end"><Button className="w-full" onClick={() => void report.refetch()}><BarChart3 />{fr ? "Appliquer" : "Apply"}</Button></div></div></section>

    <nav aria-label={fr ? "Sections du rapport" : "Report sections"} className="flex gap-2 overflow-x-auto border-b border-border pb-1">{tabs.map((item) => <button type="button" key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold transition ${tab === item.id ? "bg-brand text-white shadow-sm" : "text-ink-secondary hover:bg-surface-2 hover:text-ink"}`}>{fr ? item.fr : item.en}</button>)}</nav>

    {tab === "overview" ? <Overview data={data} fr={fr} orgSlug={orgSlug} /> : null}
    {tab === "operations" ? <Operations data={data} fr={fr} orgSlug={orgSlug} /> : null}
    {tab === "work" ? <Work data={data} fr={fr} orgSlug={orgSlug} /> : null}
    {tab === "finance" ? <Finance data={data} fr={fr} orgSlug={orgSlug} locale={locale} /> : null}
  </main>;
}

function Overview({ data, fr, orgSlug }: { data: Report; fr: boolean; orgSlug: string }) { return <section className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label={fr ? "Lots actifs" : "Active flocks"} value={data.poultry ? integer(data.poultry.activeFlocks) : "—"} detail={fr ? "aviculture" : "poultry"} icon={Bird} href={`/${orgSlug}/poultry`} /><Metric label={fr ? "Animaux actifs" : "Active animals"} value={data.pigs ? integer(data.pigs.activeAnimals) : "—"} detail={fr ? "élevage porcin" : "pig operations"} icon={PiggyBank} href={`/${orgSlug}/pigs`} /><Metric label={fr ? "Plantations actives" : "Active plantings"} value={data.agriculture ? integer(data.agriculture.activePlantings) : "—"} detail={fr ? "agriculture" : "agriculture"} icon={Sprout} href={`/${orgSlug}/agriculture`} /><Metric label={fr ? "Employés actifs" : "Active employees"} value={data.people ? integer(data.people.activeEmployees) : "—"} detail={data.people ? `${integer(data.people.onLeave)} ${fr ? "en congé" : "on leave"}` : fr ? "accès limité" : "limited access"} icon={UsersRound} href={`/${orgSlug}/employees`} /></div><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><ReportPanel title={fr ? "Décisions à traiter" : "Decisions to address"} subtitle={fr ? "Les éléments qui demandent une action ou une vérification rapide." : "Items requiring quick action or verification."}><div className="divide-y divide-border"><Decision tone="red" label={fr ? "Alertes critiques" : "Critical alerts"} value={data.governance.criticalAlerts} href={`/${orgSlug}/alerts`} fr={fr} /><Decision tone="amber" label={fr ? "Tâches en retard" : "Overdue tasks"} value={data.work?.overdueTasks ?? 0} href={`/${orgSlug}/tasks`} fr={fr} /><Decision tone="amber" label={fr ? "Stock faible" : "Low stock"} value={data.inventory?.lowStock ?? 0} href={`/${orgSlug}/inventory`} fr={fr} /><Decision tone="blue" label={fr ? "Approbations en attente" : "Pending approvals"} value={data.governance.pendingApprovals} href={`/${orgSlug}/approvals`} fr={fr} /></div></ReportPanel><ReportPanel title={fr ? "Vue de portefeuille" : "Portfolio view"} subtitle={fr ? "Suivi de la coordination de l’entreprise." : "Company coordination at a glance."}><div className="grid grid-cols-2 gap-3"><Compact label={fr ? "Projets actifs" : "Active projects"} value={data.governance.activeProjects} /><Compact label={fr ? "Rapports terrain" : "Field reports"} value={data.work?.dailyReports ?? 0} /><Compact label={fr ? "À revoir" : "To review"} value={data.work?.awaitingReview ?? 0} /><Compact label={fr ? "Commandes ouvertes" : "Open orders"} value={data.procurement?.openOrders ?? 0} /></div></ReportPanel></div></section>; }
function Operations({ data, fr, orgSlug }: { data: Report; fr: boolean; orgSlug: string }) { const empty = !data.poultry && !data.pigs && !data.agriculture; if (empty) return <Restricted fr={fr} />; return <section className="grid gap-5 xl:grid-cols-3">{data.poultry ? <ReportPanel title={fr ? "Aviculture" : "Poultry"} subtitle={fr ? "État des lots et production de la période." : "Flock state and production in the period."} action={<ModuleLink href={`/${orgSlug}/poultry`} fr={fr} />}><StatRows rows={[[fr ? "Lots actifs" : "Active flocks", data.poultry.activeFlocks, ""],[fr ? "Oiseaux vivants" : "Live birds", data.poultry.liveBirds, ""],[fr ? "Mortalité" : "Mortality", data.poultry.mortality, ""],[fr ? "Aliment distribué" : "Feed issued", data.poultry.feedKg, "kg"],[fr ? "Œufs collectés" : "Eggs collected", data.poultry.eggs, ""]]} /></ReportPanel> : null}{data.pigs ? <ReportPanel title={fr ? "Élevage porcin" : "Pig operations"} subtitle={fr ? "Animaux, enclos et alimentation enregistrés." : "Animals, pens and recorded feed."} action={<ModuleLink href={`/${orgSlug}/pigs`} fr={fr} />}><StatRows rows={[[fr ? "Enclos" : "Pens", data.pigs.pens, ""],[fr ? "Animaux actifs" : "Active animals", data.pigs.activeAnimals, ""],[fr ? "Mortalité" : "Mortality", data.pigs.mortality, ""],[fr ? "Aliment distribué" : "Feed issued", data.pigs.feedKg, "kg"]]} /></ReportPanel> : null}{data.agriculture ? <ReportPanel title={fr ? "Agriculture" : "Agriculture"} subtitle={fr ? "Parcelles, travaux et récoltes dans le périmètre." : "Fields, work and harvests in scope."} action={<ModuleLink href={`/${orgSlug}/agriculture`} fr={fr} />}><StatRows rows={[[fr ? "Fermes" : "Farms", data.agriculture.farms, ""],[fr ? "Champs" : "Fields", data.agriculture.fields, ""],[fr ? "Plantations actives" : "Active plantings", data.agriculture.activePlantings, ""],[fr ? "Récoltes" : "Harvests", data.agriculture.harvests, ""],[fr ? "Récolté" : "Harvested", data.agriculture.harvestKg, "kg"]]} /></ReportPanel> : null}</section>; }
function Work({ data, fr, orgSlug }: { data: Report; fr: boolean; orgSlug: string }) { if (!data.work) return <Restricted fr={fr} />; return <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><ReportPanel title={fr ? "Exécution du travail" : "Work execution"} subtitle={fr ? "Les tâches sont les mêmes dans les espaces Projet, Tâches et Travail quotidien." : "These are the same tasks used in Projects, Tasks and Daily work."} action={<ModuleLink href={`/${orgSlug}/tasks`} fr={fr} />}><div className="grid gap-3 sm:grid-cols-3"><Metric label={fr ? "Ouvertes" : "Open"} value={integer(data.work.openTasks)} detail={fr ? "à réaliser" : "to complete"} icon={Activity} /><Metric label={fr ? "Terminées" : "Completed"} value={integer(data.work.completedTasks)} detail={fr ? "tâches" : "tasks"} icon={BarChart3} /><Metric label={fr ? "En retard" : "Overdue"} value={integer(data.work.overdueTasks)} detail={fr ? "à relancer" : "follow up"} icon={AlertTriangle} critical={data.work.overdueTasks > 0} /></div></ReportPanel><ReportPanel title={fr ? "Conformité terrain" : "Field compliance"} subtitle={fr ? "Rapports soumis pendant la période sélectionnée." : "Reports submitted in the selected period."} action={<ModuleLink href={`/${orgSlug}/daily-work`} fr={fr} />}><StatRows rows={[[fr ? "Rapports terrain" : "Field reports", data.work.dailyReports, ""],[fr ? "En attente de revue" : "Awaiting review", data.work.awaitingReview, ""],[fr ? "Alertes ouvertes" : "Open alerts", data.governance.openAlerts, ""],[fr ? "Approbations en attente" : "Pending approvals", data.governance.pendingApprovals, ""]]} /></ReportPanel></section>; }
function Finance({ data, fr, orgSlug, locale }: { data: Report; fr: boolean; orgSlug: string; locale: string }) { if (!data.finance && !data.inventory && !data.procurement) return <Restricted fr={fr} />; return <section className="space-y-5"><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">{data.finance ? <ReportPanel title={fr ? "Contrôle financier" : "Financial control"} subtitle={fr ? "Budget projet et dépenses approuvées/payées par devise. Une dépense n’est comptée qu’une fois." : "Project budget and approved/paid spending by currency. Each expense is counted once."} action={<ModuleLink href={`/${orgSlug}/projects`} fr={fr} />}><div className="space-y-3">{data.finance.currencies.length ? data.finance.currencies.map((row) => <div key={row.currency} className="rounded-xl border border-border bg-surface-2 p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-ink">{row.currency}</p><Badge variant={row.available < 0 ? "serious" : "good"}>{row.available < 0 ? (fr ? "Dépassement" : "Over budget") : (fr ? "Disponible" : "Available")}</Badge></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><MiniMoney label={fr ? "Prévu" : "Planned"} value={money(row.planned, row.currency, locale)} /><MiniMoney label={fr ? "Dépensé" : "Spent"} value={money(row.approvedExpenses, row.currency, locale)} /><MiniMoney label={fr ? "Disponible" : "Available"} value={money(row.available, row.currency, locale)} /></div></div>) : <EmptyState icon={Wallet} title={fr ? "Aucune ligne financière dans ce périmètre" : "No financial lines in this scope"} description={fr ? "Les budgets projet et dépenses approuvées apparaîtront ici." : "Project budgets and approved expenses will appear here."} />}</div></ReportPanel> : null}<ReportPanel title={fr ? "Ressources & achats" : "Resources & purchasing"} subtitle={fr ? "Le stock réel et les achats restent gérés dans leurs modules partagés." : "Physical stock and purchasing remain managed in their shared modules."}><div className="space-y-3"><Compact label={fr ? "Articles en stock" : "Stock items"} value={data.inventory?.items ?? 0} /><Compact label={fr ? "Entrepôts" : "Warehouses"} value={data.inventory?.warehouses ?? 0} /><Compact label={fr ? "Demandes à traiter" : "Requests to handle"} value={data.procurement?.awaitingRequests ?? 0} /><Compact label={fr ? "Commandes reçues" : "Orders received"} value={data.procurement?.receivedOrders ?? 0} /></div><div className="mt-4 flex gap-2"><ModuleLink href={`/${orgSlug}/inventory`} fr={fr} /><ModuleLink href={`/${orgSlug}/procurement`} fr={fr} /></div></ReportPanel></div></section>; }
function Filter({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-xs font-semibold text-ink-secondary"><span>{label}</span>{children}</label>; }
function HeroMetric({ label, value, note, icon: Icon, danger }: { label: string; value: string; note?: string; icon: typeof Activity; danger?: boolean }) { return <div className={`rounded-2xl border p-4 ${danger ? "border-rose-200/35 bg-rose-950/15" : "border-white/15 bg-white/10"}`}><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium text-sky-100">{label}</p><Icon className={`size-4 ${danger ? "text-rose-200" : "text-emerald-200"}`} /></div><p className="mt-2 text-xl font-semibold tabular-nums text-white">{value}</p>{note ? <p className="mt-1 text-xs text-sky-100/80">{note}</p> : null}</div>; }
function Metric({ label, value, detail, icon: Icon, href, critical = false }: { label: string; value: string; detail: string; icon: typeof Activity; href?: string; critical?: boolean }) { const body = <><div className={`grid size-10 place-items-center rounded-xl ${critical ? "bg-rose-500/12 text-rose-600 dark:text-rose-300" : "bg-brand-subtle text-brand"}`}><Icon className="size-5" /></div><p className="mt-5 text-xs font-semibold uppercase tracking-wide text-ink-muted">{label}</p><p className="mt-1 text-3xl font-semibold tracking-[-.04em] text-ink">{value}</p><p className="mt-1 text-xs text-ink-secondary">{detail}</p></>; return href ? <Link href={href} className="rounded-2xl border border-border bg-surface-1 p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-brand/35 hover:shadow-md">{body}</Link> : <div className="rounded-2xl border border-border bg-surface-1 p-5 shadow-sm">{body}</div>; }
function ReportPanel({ title, subtitle, action, children }: { title: string; subtitle: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-surface-1 p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-ink">{title}</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-ink-secondary">{subtitle}</p></div>{action}</div><div className="mt-5">{children}</div></section>; }
function Decision({ tone, label, value, href, fr }: { tone: "red" | "amber" | "blue"; label: string; value: number; href: string; fr: boolean }) { const colors = tone === "red" ? "bg-rose-500/10 text-rose-700 dark:text-rose-300" : tone === "amber" ? "bg-amber-500/10 text-amber-700 dark:text-amber-300" : "bg-brand-subtle text-brand"; return <Link href={href} className="flex items-center justify-between gap-4 py-3 transition hover:opacity-75"><div><p className="text-sm font-semibold text-ink">{label}</p><p className="mt-0.5 text-xs text-ink-secondary">{value ? (fr ? "Une action est recommandée." : "An action is recommended.") : (fr ? "Rien à signaler dans ce périmètre." : "Nothing to report in this scope.")}</p></div><span className={`grid size-9 place-items-center rounded-xl text-sm font-bold ${colors}`}>{integer(value)}</span></Link>; }
function Compact({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-border bg-surface-2 px-4 py-3"><p className="text-xs text-ink-secondary">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums text-ink">{integer(value)}</p></div>; }
function StatRows({ rows }: { rows: Array<[string, number, string]> }) { return <dl className="space-y-3">{rows.map(([label, amount, unit]) => <div key={label} className="flex items-center justify-between gap-4 border-b border-border pb-3 last:border-0 last:pb-0"><dt className="text-sm text-ink-secondary">{label}</dt><dd className="font-semibold tabular-nums text-ink">{integer(amount)}{unit ? ` ${unit}` : ""}</dd></div>)}</dl>; }
function ModuleLink({ href, fr }: { href: string; fr: boolean }) { return <Link href={href} className="inline-flex items-center gap-1 text-xs font-semibold text-brand hover:underline">{fr ? "Ouvrir" : "Open"}<span aria-hidden>→</span></Link>; }
function MiniMoney({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-ink-muted">{label}</p><p className="mt-1 font-semibold text-ink">{value}</p></div>; }
function Restricted({ fr }: { fr: boolean }) { return <section className="rounded-2xl border border-border bg-surface-1 p-7"><EmptyState icon={ShieldAlert} title={fr ? "Aucune donnée autorisée pour cette section" : "No authorized data for this section"} description={fr ? "Votre rôle limite cette lecture aux modules qui vous sont attribués. Contactez le propriétaire si vous avez besoin d’un accès complémentaire." : "Your role limits this view to assigned modules. Contact the owner if you need additional access."} /></section>; }