-- 034_approval_workflow.sql
-- Approval numbers are company-local and generated by the database, so no
-- caller can accidentally duplicate one while two managers submit work.

CREATE TABLE management_approval_number_counters (
  organization_id uuid PRIMARY KEY REFERENCES organizations (id) ON DELETE CASCADE,
  last_number     integer NOT NULL DEFAULT 0 CHECK (last_number >= 0)
);
SELECT enable_tenant_rls('management_approval_number_counters');

CREATE OR REPLACE FUNCTION management_assign_approval_number()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  next_number integer;
BEGIN
  IF NEW.approval_number IS NOT NULL AND btrim(NEW.approval_number) <> '' THEN
    RETURN NEW;
  END IF;

  INSERT INTO management_approval_number_counters (organization_id, last_number)
  VALUES (NEW.organization_id, 1)
  ON CONFLICT (organization_id) DO UPDATE
    SET last_number = management_approval_number_counters.last_number + 1
  RETURNING last_number INTO next_number;

  NEW.approval_number := 'APP-' || lpad(next_number::text, 5, '0');
  RETURN NEW;
END;
$$;

CREATE TRIGGER management_approval_requests_assign_number
  BEFORE INSERT ON management_approval_requests
  FOR EACH ROW EXECUTE FUNCTION management_assign_approval_number();