-- Every employee payslip needs its own stable, non-guessable document number.
-- The CO prefix identifies a company-issued payroll document; the following
-- 16 digits are generated by PostgreSQL when the payslip is created.
ALTER TABLE payslips
  ADD COLUMN IF NOT EXISTS reference text;

ALTER TABLE payslips
  ALTER COLUMN reference SET DEFAULT (
    'CO-' ||
    lpad((floor(random() * 100000000))::bigint::text, 8, '0') ||
    lpad((floor(random() * 100000000))::bigint::text, 8, '0')
  );

-- Existing approved payslips are frozen by design. During this schema upgrade we
-- temporarily disable only their two update triggers so the new document number
-- can be backfilled; figures, lines and approval state are never changed.
ALTER TABLE payslips DISABLE TRIGGER payslips_frozen;
ALTER TABLE payslips DISABLE TRIGGER payslips_set_updated_at;

UPDATE payslips
   SET reference = DEFAULT
 WHERE reference IS NULL OR btrim(reference) = '';

ALTER TABLE payslips ENABLE TRIGGER payslips_set_updated_at;
ALTER TABLE payslips ENABLE TRIGGER payslips_frozen;

ALTER TABLE payslips
  ALTER COLUMN reference SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint
     WHERE conname = 'payslips_reference_format'
  ) THEN
    ALTER TABLE payslips
      ADD CONSTRAINT payslips_reference_format
      CHECK (reference ~ '^CO-[0-9]{16}$');
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS payslips_reference_unique_per_org
  ON payslips (organization_id, reference);