-- Purchase references are generated by the database so every tenant receives
-- a stable, concurrent-safe sequence without users typing document numbers.

CREATE TABLE management_purchase_request_number_counters (
  organization_id uuid PRIMARY KEY REFERENCES organizations (id) ON DELETE CASCADE,
  last_number     integer NOT NULL DEFAULT 0 CHECK (last_number >= 0)
);
SELECT enable_tenant_rls('management_purchase_request_number_counters');

CREATE TABLE management_purchase_order_number_counters (
  organization_id uuid PRIMARY KEY REFERENCES organizations (id) ON DELETE CASCADE,
  last_number     integer NOT NULL DEFAULT 0 CHECK (last_number >= 0)
);
SELECT enable_tenant_rls('management_purchase_order_number_counters');

-- Preserve the sequence position if an organization already has generated
-- DA-/BC- references from a prior installation.
INSERT INTO management_purchase_request_number_counters (organization_id, last_number)
SELECT organization_id,
       COALESCE(MAX(CASE WHEN request_number ~ '^DA-[0-9]+$'
                         THEN substring(request_number FROM 4)::integer
                         ELSE 0 END), 0)
FROM management_purchase_requests
GROUP BY organization_id
ON CONFLICT (organization_id) DO UPDATE
  SET last_number = GREATEST(
    management_purchase_request_number_counters.last_number,
    EXCLUDED.last_number
  );

INSERT INTO management_purchase_order_number_counters (organization_id, last_number)
SELECT organization_id,
       COALESCE(MAX(CASE WHEN order_number ~ '^BC-[0-9]+$'
                         THEN substring(order_number FROM 4)::integer
                         ELSE 0 END), 0)
FROM management_purchase_orders
GROUP BY organization_id
ON CONFLICT (organization_id) DO UPDATE
  SET last_number = GREATEST(
    management_purchase_order_number_counters.last_number,
    EXCLUDED.last_number
  );

CREATE OR REPLACE FUNCTION management_assign_purchase_request_number()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  next_number integer;
BEGIN
  INSERT INTO management_purchase_request_number_counters (organization_id, last_number)
  VALUES (NEW.organization_id, 1)
  ON CONFLICT (organization_id) DO UPDATE
    SET last_number = management_purchase_request_number_counters.last_number + 1
  RETURNING last_number INTO next_number;

  NEW.request_number := 'DA-' || lpad(next_number::text, 6, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS management_purchase_requests_assign_number
  ON management_purchase_requests;
CREATE TRIGGER management_purchase_requests_assign_number
  BEFORE INSERT ON management_purchase_requests
  FOR EACH ROW EXECUTE FUNCTION management_assign_purchase_request_number();

CREATE OR REPLACE FUNCTION management_assign_purchase_order_number()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  next_number integer;
BEGIN
  INSERT INTO management_purchase_order_number_counters (organization_id, last_number)
  VALUES (NEW.organization_id, 1)
  ON CONFLICT (organization_id) DO UPDATE
    SET last_number = management_purchase_order_number_counters.last_number + 1
  RETURNING last_number INTO next_number;

  NEW.order_number := 'BC-' || lpad(next_number::text, 6, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS management_purchase_orders_assign_number
  ON management_purchase_orders;
CREATE TRIGGER management_purchase_orders_assign_number
  BEFORE INSERT ON management_purchase_orders
  FOR EACH ROW EXECUTE FUNCTION management_assign_purchase_order_number();